---
- name: Testing Handlers
  hosts: all
  tasks:
  - name: Install Dotnet4.6.1
    win_chocolatey:
      name: winrar
      state: present
    notify:
    - reboot server
  - name: failing the tasks
    debug:
      msg: failing the task as Testing requires
    failed_when: true
    ignore_errors: true
  - name: this is another task
    debug: 
      final task
  handlers:
  - name: reboot server
    win_reboot: