---
- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - block:
    - name: block
      win_chocolatey:
        name: flashplayerpp
        state: present
    rescue:
    - name: rollback
      win_chocolatey:
        name: flashplayerppapi
        state: absent
    always: 
    - name: I will always run
      debug:
        msg: no one can stop me
  - name: this is another task
    debug: 
      msg: Hello World