---
- name: Simple Boolean Task Demo 
  hosts: all
  vars:
    run_my_task: true
  tasks:
    - name: Install IIS web-server with sub-features and management tools
      win_feature: 
        name: Web-server
        state: present
        include_sub_feature: true
        include_management_tools: true
      when: run_my_task
      register: feature_output

    - name: Reboot if installing web-server feature requires installing
      win_reboot:
      when: feature_output.reboot_required